### ISSUE TITLE
Bug? 新的固件无法为有线分配IP

### ISSUE THREAD

**Issue by duchenpaul** [ibook86/newifi3-d2-openwrt#10]
我用uboot刷了你的最新的固件[OpenWrt_firmware_d-team_newifi-d2_202108091259](https://github.com/ibook86/newifi3-d2-openwrt/suites/3443848606/artifacts/81693803)后发现有线无法分配IP, 无论静态还是DHCP, 然后我刷回之前版本 (OpenWrt R21.4.18 / LuCI Master (git-21.114.56541-974fb04) 内核: 5.4.117) 是好的.

我fork了你的项目 然后自己用master分支编译, 还是有问题.

我还没有看你的提交记录, 我准备从你之前的版本根据我的需求做派生, 但是目前没定位到我当是下的是哪个版本的...

**Comment by duchenpaul** [comment]
可能是这个commit 43f2fcb72168108e4239cab38ead3b1e0fbcd75e

**Comment by duchenpaul** [comment]
但是没有config file 我没法定位问题 😞

**Comment by duchenpaul** [comment]
请求提供 43f2fcb 这个commit的config 文件

**Comment by ibook86** [comment]
> 请求提供 [43f2fcb](https://github.com/ibook86/newifi3-d2-openwrt/commit/43f2fcb72168108e4239cab38ead3b1e0fbcd75e) 这个commit的config 文件

压缩包OpenWrt_firmware_d-team_newifi-d2_202108091259里有个config.buildinfo就是该固件对应的config文件，和本项目根目录的config文件一样

日用下载release版本的就行，一般lean有大更新日志了我才发一个release，没必要追新用action的，我自用的就是release，OpenWrt_firmware_d-team_newifi-d2_202108091259这个版本我还没测过

**Comment by duchenpaul** [comment]
你用的是具体哪一个? 可以给我一个链接么 谢谢!

**Comment by ibook86** [comment]
> 你用的是具体哪一个? 可以给我一个链接么 谢谢!

上面已经说过了，搞不懂为啥还要问第二次，建议仔细看看再提问

**Comment by duchenpaul** [comment]
因为`OpenWrt_firmware_d-team_newifi-d2_202108091259` 这个有问题呀, 所以问问你用的是哪个版本, 你如果用的也是这个版本的 我就会查查我的问题

**Comment by ibook86** [comment]
https://github.com/ibook86/newifi3-d2-openwrt/releases
