### ISSUE TITLE
提问前请阅读《提问的智慧》(github不是IM)

### ISSUE THREAD

**Issue by ibook86** [ibook86/newifi3-d2-openwrt#11]
我们相信每个人的时间都十分宝贵，所以请在提问前仔细阅读《提问的智慧》，然后再提问，同时如果您有好的意见和想法也可以提出，或者提交pr，感谢

以下为简体中文版的
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

注意：这里不是IM

**Comment by lincanbin** [comment]
无法识别U盘，是已知问题还是只有我这样？

**Comment by ibook86** [comment]
> USB



> 
> 
> 无法识别U盘，是已知问题还是只有我这样？ USB存储相关的kmod包也装不上 ![image](https://user-images.githubusercontent.com/5785188/139527716-7ab54bf6-b175-4263-9cfa-a0e374f6165a.png)

看报错是缺内核模块，你可以在make menuconfig界面->Block Devices里面把scsi选上用action编译下

我没u盘设备，没测过usb，并且一般新三不建议用usb，会影响无线性能

或者欢迎提交pr

**Comment by lincanbin** [comment]
> > USB
> 
> > 无法识别U盘，是已知问题还是只有我这样？ USB存储相关的kmod包也装不上 ![image](https://user-images.githubusercontent.com/5785188/139527716-7ab54bf6-b175-4263-9cfa-a0e374f6165a.png)
> 
> 看报错是缺内核模块，你可以在make menuconfig界面->Block Devices里面把scsi选上用action编译下
> 
> 我没u盘设备，没测过usb，并且一般新三不建议用usb，会影响无线性能
> 
> 后面有时间我再考虑加上
> 
> 或者欢迎提交pr

USB 3.0只是会干扰2.4GHz，但是这个频段我用不到的，我的设备基本都是5GHz。
主要还是新3的闪存太小了，想挂个U盘跑点自己写的小东西。

要是能抽空加上U盘的支持就好了，非常感谢。

**Comment by ibook86** [comment]
> 
> 
> > > USB
> > 
> > 
> > > 无法识别U盘，是已知问题还是只有我这样？ USB存储相关的kmod包也装不上 ![image](https://user-images.githubusercontent.com/5785188/139527716-7ab54bf6-b175-4263-9cfa-a0e374f6165a.png)
> > 
> > 
> > 看报错是缺内核模块，你可以在make menuconfig界面->Block Devices里面把scsi选上用action编译下
> > 我没u盘设备，没测过usb，并且一般新三不建议用usb，会影响无线性能
> > 后面有时间我再考虑加上
> > 或者欢迎提交pr
> 
> USB 3.0只是会干扰2.4GHz，但是这个频段我用不到的，我的设备基本都是5GHz。 主要还是新3的闪存太小了，想挂个U盘跑点自己写的小东西。
> 
> 要是能抽空加上U盘的支持就好了，非常感谢。

可以，下回push加上

**Comment by ibook86** [comment]
> 无法识别U盘，是已知问题还是只有我这样？ USB存储相关的kmod包也装不上 ![image](https://user-images.githubusercontent.com/5785188/139527716-7ab54bf6-b175-4263-9cfa-a0e374f6165a.png)

已支持U盘自动挂载，插上U盘即可识别
