### ISSUE TITLE
opkg install kmod-ipt-nat6 报错

### ISSUE THREAD

**Issue by qqisee** [ibook86/newifi3-d2-openwrt#13]
使用的是最新的release版本，安装install kmod-ipt-nat6这个的时候报错
```
pkg_hash_fetch_best_installation_candidate: Packages for kmod-ipt-nat6 found, but incompatible with the architectures configured
```
我也尝试了网上的方法加上这几句
```
arch all 100
arch mipsel1004kcdsp 200
arch mipsel 300
arch ralink 400
arch ralink1004kcdsp 500
arch mips 600
arch unkown 700
```
但是也没有用
所以还是来问一下

**Comment by ibook86** [comment]
https://mirrors.tuna.tsinghua.edu.cn/openwrt/releases/21.02.0-rc4/targets/ramips/mt7621/packages/kmod-ipt-nat6_5.4.137-1_mipsel_24kc.ipk
下载这个手动安装下
下次可以考虑直接编译到固件里面

**Comment by qqisee** [comment]
![图片](https://user-images.githubusercontent.com/25243560/131772046-b6592eb7-7533-4354-9286-eb77c3c90d2c.png)
安装kmod-nf-nat6_5.4.137-1_mipsel_24kc.ipk 报的这个错误
![图片](https://user-images.githubusercontent.com/25243560/131772159-852ae47c-d9af-4c76-965c-e289637134e4.png)
错误还是和之前一样的

**Comment by ibook86** [comment]
> ![图片](https://user-images.githubusercontent.com/25243560/131772046-b6592eb7-7533-4354-9286-eb77c3c90d2c.png)
> 安装kmod-nf-nat6_5.4.137-1_mipsel_24kc.ipk 报的这个错误
> ![图片](https://user-images.githubusercontent.com/25243560/131772159-852ae47c-d9af-4c76-965c-e289637134e4.png)
> 错误还是和之前一样的
![131772159-852ae47c-d9af-4c76-965c-e289637134e4__01](https://user-images.githubusercontent.com/39795988/131774487-bc1964f9-1485-4a75-9995-75b0fe482c94.png)

这是缺依赖，意思是这些提示的依赖都缺少，需要先安装图上提示的这些依赖软件包才能安装kmod-ipt-nat6，你可以换成清华源用opkg命令批量安装，或者等我下一版直接编译到估计里面

**Comment by qqisee** [comment]
坐等下一版

**Comment by ibook86** [comment]
> 
> 
> 坐等下一版

下载这个，已经集成了，看看有问题没有 我没v6测不了 https://github.com/ibook86/newifi3-d2-openwrt/actions/runs/1200091812
后面默认都会集成这个模块

**Comment by qqisee** [comment]
我刷了immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade这个是可以的，可以获得ipv6
openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade 这个获取不了，这个里面可能是少kmod-ipt-nat6吧

**Comment by ibook86** [comment]
immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin是编译的，用这个就行；
用ImmortalWrt分支源码编译时，里面的openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin是自动生成的，内核就没immortalwrt-xxx的新，估计是op官方的，不用管，凡是ImmortalWrt分支的源码编译的我就没刷过后者这个固件
