### ISSUE TITLE
使用迅雷时，ksoftirqd负载高，直接拉爆路由器，连访问内网都响应极慢

### ISSUE THREAD

**Issue by lincanbin** [ibook86/newifi3-d2-openwrt#17]
![image](https://user-images.githubusercontent.com/5785188/142457962-347ffb6f-4cdc-402f-a5d0-863a073c8885.png)

架构 | MediaTek MT7621 ver:1 eco:3
-- | --
固件版本 | ImmortalWrt 21.02-SNAPSHOT r18963-38244af32c / LuCI openwrt-21.02 branch git-21.301.66596-f28aaa3
内核版本 | 5.4.154
本地时间 | 2021-11-19 00:37:39
运行时间 | 19d 7h 38m 33s
平均负载 | 8.64, 8.50, 8.73

此时下载速度不过2MB/s

**Comment by ibook86** [comment]
迅雷跑上行吸血连接数太多了吗？电脑没迅雷 无法复现

**Comment by EzrealC** [comment]
跑PT也有这个问题，看来只要有p2p的都受影响

**Comment by EzrealC** [comment]
现在在用[](https://github.com/Cathgao/newifi3)这个固件，就一切正常了
