### ISSUE TITLE
提问: bin 的文件夹用处

### ISSUE THREAD

**Issue by duchenpaul** [ibook86/newifi3-d2-openwrt#9]
我看bin下面有很多二进制文件,但是在action里面似乎没有用到, 问下这里面的文件有什么用处?

**Comment by duchenpaul** [comment]
另外 build-openwrt-immortalwrt 这个是干啥的?

**Comment by ibook86** [comment]
1.bin是早期我手动编译生成的全部二进制文件(早期没有使用action编译)，包含固件和软件包，一块上传了
2.这是编译另一个openwrt分支源码用的，软件包比较高大全一点，只不过感觉稳定性没那么好
